export const associationConfig = {
  legalName: "ASSOCIAÇÃO ESPORTIVA SAF TALISMA",
  institutionalName: "Associação Esportiva SAF/Talismã",
  shortName: "Associação SAF/Talismã",
  displayName: "SAF/Talismã",
  name: "Associação Esportiva SAF/Talismã",
  slogan: "Esporte, formação e desenvolvimento de atletas em Arapoti e nos Campos Gerais do Paraná",
  description: "Esporte, formação e desenvolvimento de atletas em Arapoti e nos Campos Gerais do Paraná.",
  cnpj: "78.597.978/0001-70",
  phone: "(41) 99754-4010",
  phoneRaw: "5541997544010",
  email: "contato@saftalisma.com.br",
  operationalEmail: "saftalisma1@gmail.com",
  domain: "saftalisma.com.br",
  url: "https://saftalisma.com.br",
  website: "https://saftalisma.com.br",
  legalAddress: {
    street: "Rua Pedro Amaral Prestes",
    number: "1014",
    city: "Arapoti",
    state: "PR",
    postalCode: "",
  },
  sportsLocation: {
    name: "Ginásio de Esportes Chapelão",
    street: "Rua das Rosas",
    number: "237",
    city: "Arapoti",
    state: "PR",
    postalCode: "84990-000",
    mapEmbedUrl: "https://www.google.com/maps?q=Gin%C3%A1sio%20de%20Esportes%20Chapel%C3%A3o%2C%20Rua%20das%20Rosas%2C%20237%2C%20Arapoti%2C%20PR%2C%2084990-000&output=embed",
    mapRouteUrl: "https://www.google.com/maps/dir/?api=1&destination=Gin%C3%A1sio%20de%20Esportes%20Chapel%C3%A3o%2C%20Rua%20das%20Rosas%2C%20237%2C%20Arapoti%2C%20PR%2C%2084990-000",
  },
  location: "Arapoti, Paraná",
  region: "Campos Gerais do Paraná",
  founded: 2009,
  social: {
    instagram: "https://instagram.com/saftalisma",
    youtube: "",
    facebook: "",
  },
};

export const developerCredit = {
  name: "NorthWay Assessoria de Marketing",
  url: "",
  logoUrl: "",
  visible: true,
};
